language: java
notifications:
  slack: mishima-group:8zsPeLEBTdLyT7kCZdQzIx4c
deploy:
  provider: heroku
  api_key:
    secure: DxVQMPgHTNGuxLI35mKmRcaMLYDSEtUlBvsHg4aP6RDYLyMaIguSg7dliEthiD1X54TOqvE0amuMDxQrz2MRi1nJlv0KWTjXjnqbLoXG5N7le7Ky6ifD9NkmCHF+IjF9pRWV597VDri/zjXmmsEEuDo2MsmJEBjkBF3BkKkO0dQxzPdkoi+CaRd0vkg5o3R+1tHe5svgOtAklq0BQAvK72mAAQcVtQChJjuefeAwdtT/+o7ctqcUGX7Y3AT0R0fS9wBBkVr3veYYaiIj+zaEUneI2ObDmabQGdEhK8+Mk6c2QzvYjSIYfWJfMhF3DdWK8mGYrcMO9AGRU7Rfx4grihHW9nbItGIHgAEo2kz0Xyto7crQAndxLTwkK4cVN0ZrNhKCBfHL5y+vyayqE48ee1ayqD+WhmlLRUCXaJUuN2B+SdkCpyFwcR8/rmkzVSMiGx6P0171TaEdNIPI9ry2ANNmW4jPmbbZuzhQkJLSFgIsmOFsDFOOrahXaUWz2Z+EhhpHAkMEd/E8Tyanv9gBkGkLXyBNtwY/dvDa05CVaK+ifPtz7gaLqdL4QCtIOczFvvtG8cVUKFucxLMVUxw+vOBWEfiW0MKJsby/7lruPrxKW+2GBF8NQqPnHtN2IJeg1rNOAHgO+vsMw+9t9OkvTaKkiacUMGZxiAM3SS8TRRI=
