language: java
notifications:
  slack: mishima-group:8zsPeLEBTdLyT7kCZdQzIx4c
deploy:
  provider: heroku
  api-key:
    secure: ZR6SqK5lfQVPj6wf1UA1VHTPs/D/2kaVSL5QWLUVeEhQr/s92YLH8iZGXYkC9rg10c1g6auDfmKbKC8OtClj+A+fvjCX/uu9NAaBhgL8XN2Oqqx43TXjmXFMtCBEcBdXFlMMkWy3i5kjpHPzXz9csIQ6LOAXrRcXoWoYOBPA0xngFwHgqGfxtix8MYNRlzZwncz1mi5N7vcfYO/dcqVsxnYM/DQrePImlmmJavhn09YNiOJjs2cqUjMOIURVpnEAm2phI6xQKo9ZwBiFe160NRxyATxODU4xLDEF1LmuSzDPuZyGdQOJZ3b/0LiRhJMAqZPGr0fCWA+cejLpKWhk1N/orxIa5hx7bBk7bEjBIfoNPD4AUbmNO3xjV3ZcmVGSCdEnYB7yET1OUvDYsxV38VLvYPVrUFaIx6P2XwPy7/APMxUVgvvwFxmw3jrDIyszICSgwVc4ThrrH97b9YxW37PpCvwlLRaR9uB9yr2+uJ/BkdvCvjzYjrJv/klAEj5UixolTZefUJ9Q1LiL+zD9eUOMRBae/FF1Ta7uYvH3r/wGOR5MqywrJ1Yzj9jb7wORsshZ84oiiH/hBNZPGtFheRiiKccLJ9PDtP+EBDK2KeORbwaTrXZahcNZ2stEADPfjb7FpIDCtzLAqj8UQ/LE8+6jEMYauV+kyjPg+r+jI84=